language: python # This lets us use newer python versions from virtualenv
python: "3.5"
compiler: clang
dist: xenial
sudo: false

branches:
  only:
  - master

env:
  global:
    - TRAVIS_TIMESTAMP=$(date +%s)
    - TRAVIS_AVAILABLE_TIME=150 # in minutes
    - TRAVIS_UPLOAD_TIME=5 # time considered to start the machine and the container (minutes)

matrix:
  fast_finish: true

# Install dependencies
install:
  - pip install -r code/requirements.txt
  - pip install coveralls

script:
  - python code/tests/test.py
